// SQL DATABASE CONNECTION. RETURN A CONNECTION OBJECT ALLOWING TO RUN QUERIES

import mysql from 'mysql2'

// 2 WAYS TO CONNECT TO SQL DB --- 1) CREATE NEWCONNECTION AND DISCONNECT FOR EVERY NEW QUERY => INEFFICIENT AND PERFORMANCE COST; 2) BETTER OPTION IS TO CREATE A CONNECTION POOL - POOL OF MULTIPLE CONNECTIONS TO RUN MULTIPLE QUERIES SIMULTANEOUSLY (EACH QUERY NEEDS ITS OWNCONNECTION)

const pool = mysql.createPool({
 // JS OBJECT CONTAINING INFORMATION ABOUT DB HOST CONNECTING TO
 host: 'localhost', //SERVER IP OR NAME
 user: 'root', // DEFAULT NAME PROVIDED DURING SQL DB CONFIGURATION
 database: 'node-udemy', // SERVER MAY HAVE MULTIPLE DATABASES, THEREFORE DATABASE SCHEMA WANT TO CONNECT TO
 password: 'Niyati@123', // PASSWORD ASSIGNEDDURING INSTALLATION
})

export default pool.promise(); // HANDLE ASYNCHRONOUS TASKS INSTEADOF CALLBACKS ALLOWING TO WRITE CODE INA MORE STRUCTURED WAY